import SiteFooter from "@/components/SiteFooter";
import SiteHeadder from "@/components/SiteHeadder";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce (Product Landing Pages)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <>
        <SiteHeadder />
        <SiteFooter />
      </>
    </>
  );
}
